# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['C:\\Users\\ousmo\\.gemini\\antigravity\\scratch\\Aiko-desktop\\core\\neural_hub.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=[
        'aiohttp',
        'pydantic',
        'pydantic.deprecated.decorator',
        'cryptography',
        'psutil',
        'pyautogui',
        'pyperclip',
        'PIL',
        'requests',
        'websockets',
        'core.api.routes',
        'core.api.websocket',
        'core.api.hub_state',
        'core.api.schemas',
        'core.api.auth',
        'core.api.broadcast',
        'core.chat_engine',
        'core.unified_memory',
        'core.rag_memory',
        'core.emotion_engine',
        'core.persona',
        'core.proactive',
        'core.autonomous_agent',
        'core.mcp_bridge',
        'core.pc_manager',
        'core.card_engine',
        'core.selfie_generator',
        'core.latex_engine',
        'core.obsidian_connector',
        'core.security',
        'core.structured_logger',
        'core.infrastructure.tools.executor',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='neural_hub',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
